#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Vayu >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Vayu=/luci-static/vayu
		set luci.main.mediaurlbase=/luci-static/vayu
		commit luci
	EOF
fi

exit 0